### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Domi04151309** [PPaszkiewicz/YeelightDeviceAPI#1]
I am currently building a smart home app and this looks exactly like what I need but I don't quite get how to use it. Since I don't have a Yeelight device but still want to integrate support for them, testing is quite hard. Could you please describe how I can send commands to a bulb of which I have the IP address?

**Comment by PPaszkiewicz** [comment]
You can take a look at [simple demo activity](https://github.com/PPaszkiewicz/YeelightDeviceAPI/blob/master/demo/src/main/java/com/github/ppaszkiewicz/yeelightdeviceapi/DemoSimpleActivity.kt)

Main idea is to observe viewmodels device list, which internally handles sending and parsing announcement broadcasts, maintaining device connection pool and emitting list of devices with their up to date state. When you receive the list you can then search/filter through it to find device with given IP address.

It is possible to make connection directly using IP as shown in [this sample](https://github.com/PPaszkiewicz/YeelightDeviceAPI/blob/master/demo/src/main/java/com/github/ppaszkiewicz/yeelightdeviceapi/DemoDirectActivity.kt) but doing that won't establish broadcast scanner so it will be impossible to determine some device properties that are only provided through the broadcast (device ID, model, firmware version, supported methods).

Once you obtain the [`YeelightDevice`](https://github.com/PPaszkiewicz/YeelightDeviceAPI/blob/master/api_core/src/main/java/com/github/ppaszkiewicz/yeelight/core/YeelightDevice.java) object you can send the commands using its methods.

**Comment by Domi04151309** [comment]
Thanks for your quick reply
